### ISSUE TITLE
Оформление кода

### ISSUE THREAD

**Issue by gizeasy** [gpn-prototypes/ui-kit#101]
рассмотреть идею про использование одинаковых конфигов на всех проектах ГПН, в т.ч. на ДС — конфиги eslint, stylelint, prettier, eitorconfig итд
просто актуализировать конфиги, которые прямо сейчас уже есть в репе, чтобы не приходилось затыкать линтеры комментариями

**Comment by gizeasy** [comment]
Договорились актуализировать конфиги. И добавить запуск линтеров и тестов в Travis

**Comment by tsvetta** [comment]
@gizeasy кстати, мы создали для фронтовых проектов либу с конфигами, на следующей неделе релизнем 
https://github.com/gpn-prototypes/frontend-configs
Можете ее использовать если хотите
