### ISSUE TITLE
Добавить tooltip в дизайн-систему

### ISSUE THREAD

**Issue by daynin** [gpn-prototypes/ui-kit#127]
Перенести tooltip из конструктора в дизайн-систему (подробнее обсудим на планировании)

**Comment by daynin** [comment]
Будем делать в рамках задачи https://jira.csssr.io/browse/GDC-267

**Comment by daynin** [comment]
Сторибук http://master.dashboard-constructor.csssr.cloud/?path=/story/components-tooltip--%D1%81-%D0%BF%D0%BE%D0%B7%D0%B8%D1%86%D0%B8%D0%BE%D0%BD%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%D0%BC-%D0%BF%D0%BE-%D0%BA%D0%BE%D0%BE%D1%80%D0%B4%D0%B8%D0%BD%D0%B0%D1%82%D0%B0%D0%BC

**Comment by nekitk** [comment]
Ссылки на стори:
* [Пример с позиционированием по координатам](http://master.dashboard-constructor.csssr.cloud/?path=/docs/components-tooltip--%D1%81-%D0%BF%D0%BE%D0%B7%D0%B8%D1%86%D0%B8%D0%BE%D0%BD%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%D0%BC-%D0%BF%D0%BE-%D0%BA%D0%BE%D0%BE%D1%80%D0%B4%D0%B8%D0%BD%D0%B0%D1%82%D0%B0%D0%BC)
* [Пример с позиционированием по якорю](http://master.dashboard-constructor.csssr.cloud/?path=/story/components-tooltip--%D1%81-%D0%BF%D0%BE%D0%B7%D0%B8%D1%86%D0%B8%D0%BE%D0%BD%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%D0%BC-%D0%BF%D0%BE-%D1%8F%D0%BA%D0%BE%D1%80%D1%8E)

В нобах можно менять направление тултипа, отступ и наличие хвостика.

**Comment by fooontic** [comment]
Очень классная демка, где за курсором бегает 👍
