### ISSUE TITLE
Поддержка IE

### ISSUE THREAD

**Issue by dnazarov** [gpn-prototypes/ui-kit#133]
При просмотре в IE не применяются стили.

![](https://s182vla.storage.yandex.net/rdisk/4d1d7b24edd6458971eb7d53ba484d235f4452fee029f8a023e17bef44daf76b/5ebdcac2/lOygoJ2-cjPCRZEMTVF0utHlCxur-huil9MjpZsTzINPq2T7-0-lUi8Vc9Q6n0M-jysBDrfLV5ILukpj3P2R7A==?uid=256210502&filename=uikit-ie.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&owner_uid=256210502&hid=83bb2e382146aafde46eb0c752df6c3c&media_type=image&fsize=176346&etag=d67bf63f621ab915da52cd7af6be3cda&rtoken=VglOCTOz2QfS&force_default=yes&ycrid=na-59aa9b5977d7db9dd8fcaa94e527a724-downloader17e&ts=5a5a37f16b480&s=609eeb868ab900f94bfc290082e856383c7dab086f06460931abb633b94425a5&pb=U2FsdGVkX1_HUx7_eNqOtKNCs8xXNaP7p-Zz4WdToaTWlMCpTQxcsO4Y6zJ_3SbyEQGnV8MPuFKUaRV-MEiDOHwH1kh_l9cAhm2D5551hfU)

Скорее всего, проблема в использовании в стилях директивы var.

![](https://s162vla.storage.yandex.net/rdisk/c3023a051e51c5161ea7d70b108bfcad121ae832e2546078d054d71fe4dab497/5ebdcb59/lOygoJ2-cjPCRZEMTVF0utlCpSDSNRo5XSCGUKdCDZBFTjo03JcKL7pGxpe1i-FHefVmB21Krdc3hadVAPBNhw==?uid=256210502&filename=uikit-css.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&owner_uid=256210502&hid=d2a82509f14188e3b15b1f11910e4daa&media_type=image&fsize=22212&etag=eab0d6f7f1525e71ef2d6d8a0b1e1b81&rtoken=vZnPwA7O8eN7&force_default=yes&ycrid=na-ae78ccf788a736923b0f975a7d58463f-downloader16e&ts=5a5a38816c840&s=3eab625c96357c82c69b110b291407eeafc7ad3ab873beca3be5841f3c0cc701&pb=U2FsdGVkX18Xu3xuswDm__KX9JsdjeHvYpu40KNKPZFYuUTo4JGrD-iSQ57r9u121QwVkeP4oodcXrQjkCd4kO-6tKcIdBNRRYedGFi3KT0)

Директивы var не поддерживаются в IE. 
![](https://s128vla.storage.yandex.net/rdisk/2661dd601c0b558b6601d1d841d7ab44e3f02936314af9f396c64123a1d234ad/5ebdcbb0/lOygoJ2-cjPCRZEMTVF0usyF0g3Y9oaTY4_jDye5aK8gHu-dURRVXPya2uA3YRXg4QLZnbnpTN6SIY0213nAeQ==?uid=256210502&filename=2020-05-14_20-49-21.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&owner_uid=256210502&fsize=56043&etag=534c86001940903f960d102183c054b6&hid=a0190185342035a6dacee69698acdae6&media_type=image&rtoken=rj6wij3SUlsw&force_default=yes&ycrid=na-eb8ca8c9124f8bde86af157acf858a4e-downloader17f&ts=5a5a38d464c00&s=88ef1fe54c86231e8987ec1f99b7a50d9a32bdedb136159f15bde9d289bcbec7&pb=U2FsdGVkX18qToSWGYNFaAlTlT3sHjrOy9xqFrD_nuCMcmV0QCjxZ4IlyyUfamrboUfbEZ8pXeBoIKzOfmUENcfrxDR-u_uwlTRhX3CMc-Y)

**Comment by fooontic** [comment]
Данная система создаётся без оглядки на IE. IE даже 11 версии очень устаревший и очень небезопасный браузер. На данный момент система создаётся исключительно под вечно зелёные браузеры с бОльшим фокусом на хромиум браузеры.
