### ISSUE TITLE
Смена элемента для {...otherProps} в TextField

### ISSUE THREAD

**Issue by ReutovDanila** [gpn-prototypes/ui-kit#159]
Столкнулся с проблемой что props накидываются на корневой элемент div. Возможно ли сделать проброс на элемент input и textarea? 

Кейс: 
По требованиям google lighthouse на элементах формы должен быть атрибут aria-label.

**Comment by gizeasy** [comment]
@ReutovDanila Как ты видишь API?

**Comment by ReutovDanila** [comment]
По использованию так:
`<TextField aria-label="Введите логин" />`
внутри компонента ` <Input
        className={cnTextField('Input')}
        value={value || ''}
        onChange={handleChange}
        maxLength={maxLength}
        disabled={disabled}
        onBlur={handleBlur}
        onFocus={handleFocus}
        autoFocus={autoFocus}
        placeholder={placeholder}
        autoComplete={autoComplete}
        readOnly={readOnly}
        required={required}
        tabIndex={tabIndex}
        name={name}
        {...(textarea ? textareaProps : inputProps)}
        {...otherProps}
      />`

**Comment by ReutovDanila** [comment]
Так же столкнулся сегодня с еще одной проблемой. Невозможно повесить на input аттрибут id, это нужно для привязки label через htmlFor.
