### ISSUE TITLE
Добавить в библиотеку иконку панели управления масштабом

### ISSUE THREAD

**Issue by Davs777** [gpn-prototypes/ui-kit#181]
Нужно добавить иконку как компоненту (2 слева) для панели (xs, s, m) https://www.figma.com/file/d1LmFzRazBtPjWsnyW8h1U/KL-%5Bdraft%5D?node-id=0%3A1

**Comment by gizeasy** [comment]
@Davs777 я же верно понял, эту иконку?

**Comment by Davs777** [comment]
Да, именно ее
