### ISSUE TITLE
Нужен способ применить тему с контрастным цветом

### ISSUE THREAD

**Issue by nekitk** [gpn-prototypes/ui-kit#182]
В проекте подключена дефолтная тема с помощью компонента `<Theme preset={presetGpnDisplay}>`.

При этом в проекте есть тултип, который рендерится в портал в body. Т.к. классы основной темы стоят не на body, а на контейнере приложения, на порталы они не действуют и в них нужно задавать тему целиком. Для этого тултип тоже оборачиваем в `<Theme>` и с помощью useTheme получаем текущую тему.

Но для тултипа нужно использовать invert-цвет. Сейчас это получилось сделать таким образом:
```ts
const { theme } = useTheme()

return ReactDOM.createPortal(
  <Theme
    preset={{
      ...theme,
      color: {
        ...theme.color,
        primary: theme.color.invert
      }
    }}
  >
    {children}
  </Theme>
);
```
Таким образом мы задаём для портала все нужные темы размеров + ставим для цвета инвертную тему. Выглядит скорее костылём, поэтому хочется найти более правильное решение.

Как другой вариант можно взять `theme` из хука, передать его по кусочкам в cnTheme и использовать получившийся класс, но в этом варианте тоже есть несколько проблем:
1. Если в theme добавится какая-то новая опция, нужно будет не забыть пройтись по всем местам с порталами и повесить соответствующий класс
2. Для применения темы в разных местах будут использоваться разные методы, каждый со своими нюанасами. Хотелось бы, чтобы снаружи для использования темы был 1 подход.

В качестве решения могу предложить:
1. Помимо Theme, экспортировать компоненты AccentTheme и InvertTheme, которые тоже вешают все классы размеров, но класс для цвета берут из другого ключа
2. Добавить компоненту Theme проп, который будет управлять тем, какой цвет надо взять: `<Theme preset={presetGpnDisplay} color="invert">`

**Comment by gizeasy** [comment]
моджет сделать так:
```tsx
const { theme } = useTheme()

return ReactDOM.createPortal(
  <Theme preset={presetGpnDisplay}>
    <Tooltip>
  </Theme>
);
```
```
const Tooltip = () => {
   const { themeClassNames } = useTheme();
   return <div className="themeClassNames.color.invert" ></div>
}
```
тогда можно сделать компонент портала с темой

```
const PortalWithTheme = ({ preset, children }) =>{
return ReactDOM.createPortal(
  <Theme preset={preset}>
    {children}
  </Theme>
);
}
```
ну и получеться так
```
<PortalWithTheme preset={presetGpnDisplay}>
    <Tooltip>
</PortalWithTheme>
```

таким образом все компоненты ведут себя одиноково в теме в плане того где им брать цвета из акцентой темы или инвернтой темы, компоненты сами в нутри решают это. Мы только определяем тему. Более того сам пресет темы можно засунуть в контекст своего приложения и забирать ее от туда, на случай если у приложения появится смена темы.

**Comment by nekitk** [comment]
Да, так норм получилось, спасибо
