### ISSUE TITLE
ChoiceGroup: предложения по изменению API

### ISSUE THREAD

**Issue by nekitk** [gpn-prototypes/ui-kit#183]
При переходе на 1 версию кита столкнулся с тем, что новый API ChoiceGroup кажется менее удобным, чем был раньше, а в некоторых местах он не соответствует соглашениям, к которым пришли при обсуждении другой задачи.

* value является массивом даже когда передан проп `multiple=false`. кажется, было удобнее, когда тип value и onChange зависел от значения пропа multiple: при false там был просто объект, а при true массив. сейчас для одиночных ChoiceGroup приходится оборачивать/разворачивать массив.
* пропсы-геттеры кажутся неудобным решением, особенно учитывая, что они необязательные, но в них есть дефолты, которые бывает сложно найти даже в коде. в другом пр-е обсуждали подобный подход и решили, что лучше принимать в качестве айтемов объект с определённым интерфейсом, а уже снаружи пусть мапят свои данные на данные для ChoiceGroup как надо. аналогичное обсуждение по снэкбару: https://github.com/gpn-prototypes/ui-kit/pull/121#discussion_r424238734
  * как пример проблемы — без getItemKey группа не будет нормально работать, но этот проп необязательный, поэтому пришлось покопаться в исходниках, чтобы понять, что он на самом деле нужен
* проп getItemTitle не используется
* в типах сложно разобраться — пришлось копаться в исходниках, чтобы понять, какие прпосы нужны компоненту и какой у них тип. многие части пропсов обёрнуты в дженерик-типы из-за чего сложно понять их финальный тип.
* в компонент передаётся id, который никак не используется, кроме прокидывания в onChange
* в onChange прокидываются лишние данные: name и id. это обсуждали в других пр-ах.

**Comment by gizeasy** [comment]
есть еще предложение избавиться от BaseCheckGroup и в место него сделать хук, в котором реалзовать всю логику и использовать этот хук во всех компонентах где есть синг или мульти выбор, соотведственно апи которое мы придумаем будет везде одиноковое.

**Comment by gizeasy** [comment]
в value передавать item или item[]


item с зафиксированыими полями - {label}
или оставляем геттеры

надо написать примеры

**Comment by gizeasy** [comment]
```tsx
const App = () => {
  const [value, setValue] = useState(null);

  const getItemKey = (item) => item;
  const getItemLabel = (item) => item;
  const getItemIcon = (item) => item === 'один' ? Icon1 : Icon2;
  const onChange = ({ value }) => setValue(value);
  
  return(
    <div>
      <ChoiceGroup
        items={items}
        value={value}
        getItemKey={getItemKey}
        getItemLabel={getItemLabel}
        getItemIcon={getItemIcon}
        onChange={onChange}
      />
      <button onClick={send}/>
    </div>
  )
};

```

```tsx

const items = ['один', 'два'];

// если itemsForChoiceGroup будет зависит от value
// то на каждый onChange придется трансвормировать оригинальный items

const itemsForChoiceGroup = items.map(item => ({
  label: item,
  key: item,
  icon: item === 'один' ? Icon1 : Icon2;
}));

const sendData = (value) => {
  // обычно нужно отправить данные в том жке формате в каком мы их получили,
  // нужно добавлять обратную трансформацию

  const valueForSend = value.map(val => val.label);
  send(valueForSend)
};

const App = () => {
  const [value, setValue] = useState(null);
  const onChange = ({ value }) => setValue(value);

  return(
    <div>
      <ChoiceGroup
        items={itemsForChoiceGroup}
        value={value}
        onChange={onChange}
      />
      <button onClick={sendData}/>
    </div>
  )
};
```

**Comment by gizeasy** [comment]
в зависимости от multiple менять тип value, мне кажется не самой хорошей идеей. 
Думаю иметь один интерфейс value удобнее, да с одной стороны ждем 1 элемент в value если это одиночный выбор
С другой стороны очень удобно кодга все выборы из списков на форме имеют одну логику и сетер состояния можно использовать. Также если значение multiple зависит от другого поля на форме, то не прихордится менять сетер состояния.

**Comment by Inzephirum** [comment]
> в зависимости от multiple менять тип value, мне кажется не самой хорошей идеей
можно внутри компонента `value` всегда приводить к массиву, а снаружи будет зависимый от `multiple`

**Comment by Inzephirum** [comment]
по примерам: сложность второго примера будет расти быстрее при добавлении селектов, особенно если эти селекты зависимые

**Comment by nekitk** [comment]
согласен, в итоге первый пример кажется удобнее, но кажется в нём стоит подумать над необходимостью getItemkey:
* если группа текстовая или смешанная (текст + иконка), то в качестве ключа можно использовать label, т.к. выводить в группе опции с одинаковым названием кажется нелогичным
* если группа только с иконками, то в качестве ключа мы компонент использовать не сможем и в таком случае придётся указывать ключ вручную

это вполне можно отразить на уровне типов

**Comment by gizeasy** [comment]
Резюмирую:
- value сделать зависимым от multiple
- Типы Сделать более читаемыми
- Оставить гетеры, но если items простые `string[]` или `{label: string}[]` то применять дефолтный гуттер лейбла и ключа
- Почистить лишние пропсы и свойства аргумента в onChange

создал https://github.com/gpn-prototypes/ui-kit/issues/267
