### ISSUE TITLE
Выпилить зависимости

### ISSUE THREAD

**Issue by gizeasy** [gpn-prototypes/ui-kit#197]

**Comment by nekitk** [comment]
Столкнулись с проблемой из-за неиспользуемых зависимостей в ui-ките. Заменили в своём проекте `enzyme` на `react-test-renderer`, т.к. увидели его в зависимостях у ui-кита и посчитали, что так будет проще потом переносить свои компоненты в кит. Но уже потом заметили, что `react-test-renderer` в ui-ките хоть и есть в package.json, но не используется, а на самом деле используется `@testing-library/react`.

@gizeasy давай возьмём в следующий спринт, чтобы избежать таких проблем
