### ISSUE TITLE
Иконки: нет иконки телефона

### ISSUE THREAD

**Issue by stug111** [gpn-prototypes/ui-kit#315]
Столкнулся с проблемой отсутствия иконки телефона, по словам дизайнера одна должна быть в ui-kit

Тред: https://gazprom-neft.slack.com/archives/GKR41GUH3/p1596618223324400
Макет где используется иконка: https://www.figma.com/file/4O3kKKrGBcd9svlm8A8mr5/%D0%A6%D0%A3%D0%91-4-%D1%8D%D0%BA%D1%80%D0%B0%D0%BD?node-id=1833%3A0

**Comment by fooontic** [comment]
Взяли в работу

**Comment by gizeasy** [comment]
https://github.com/gpn-prototypes/ui-kit/pull/332
добавили
