### ISSUE TITLE
Attach. Исправить растяжение длины зависимых полей при длинных названиях

### ISSUE THREAD

**Issue by ilchukovaolga** [gpn-prototypes/ui-kit#317]
У файла с длинным названием поля комментария и категории длиннее

ФР: https://s.csssr.ru/UMYJTGU0M/2020-07-30-17-36-17-pvw11.jpg

Компонент: https://ui-kit.gpn.vercel.app/?path=/story/components-attach--playground
Ссылка на макеты: https://www.figma.com/file/kXPRVpLhqNfBm9DBOoaE9X/VEGA-2.0-%7B-dev-%7D?node-id=617%3A871

**Comment by gizeasy** [comment]
мне кажется проблема в родитесльком блоке он ни как не ограничивает ширину компонентов которые внутри

**Comment by ilchukovaolga** [comment]
@maksim-kononov-csssr посмотри, пожалуйста

**Comment by maksim-kononov-csssr** [comment]
Посмотрел, проблема на нашей стороне. Закрываю issue
