### ISSUE TITLE
ChoiceGroup. Добавить переключение по Tab

### ISSUE THREAD

**Issue by ilchukovaolga** [gpn-prototypes/ui-kit#335]
Необходимо добавить возможность выбрать переключатель из группы по Tab. Сейчас выбирается только первый из группы.

Ссылка на компонент: https://ui-kit.gpn.vercel.app/?path=/story/components-choicegroup--playground

**Comment by gizeasy** [comment]
@ilchukovaolga  переключение сейчас идет нативное стрелочками
@fooontic что думаешь как лучше сделать?

**Comment by fooontic** [comment]
@ilchukovaolga сейчас ChoiceGroup в случае единичного выбора сделано нативными радиокнопкамИ, а они работают со стрелочками. Вариант работы по табу обсуждался, но пока решение не было принято. Но думаю, добавим со временем. Пока есть более приоритетные задачи.

**Comment by ilchukovaolga** [comment]
@ilchukovaolga @fooontic окей, давайте оставим стрелочками. Закрываю Issue
