### ISSUE TITLE
Ошибка с типами в Button

### ISSUE THREAD

**Issue by c1n1k** [gpn-prototypes/ui-kit#337]
В версии 1.6.1 при указании для кнопки `type="button"` возникает ошибка при сборке `vega-ui` указывающая на ошибку в отсутствии допустимого html атрибута `type` c значением `button`

**Comment by gizeasy** [comment]
если просто поставить на экспорт компонент то проблем нет
```
export { Button } from '@gpn-design/uikit/Button';
```

так же если хочется модjрнизировать компонент то можно написать так:

```
import {
  Button as BaseButton,
  ButtonPropSize,
  ButtonPropView,
  ButtonPropWidth,
  ButtonPropForm,
} from '@gpn-design/uikit/Button';

import {
  ComponentWithAs,
  forwardRefWithAs,
} from '@gpn-design/uikit/__internal__/src/utils/types/PropsWithAsAttributes';
import { IconProps, IconPropSize } from '@gpn-design/uikit/Icon';

type Props = {
  size?: ButtonPropSize;
  view?: ButtonPropView;
  width?: ButtonPropWidth;
  form?: ButtonPropForm;
  tabIndex?: number;
  disabled?: boolean;
  loading?: boolean;
  label?: string | number;
  onClick?: React.EventHandler<React.MouseEvent>;
  iconLeft?: React.FC<IconProps>;
  iconRight?: React.FC<IconProps>;
  onlyIcon?: boolean;
  iconSize?: IconPropSize;
  title?: string;
  children?: never;
};

export const Button: ComponentWithAs<Props, 'button'> = forwardRefWithAs<Props>((props, ref) => {
  return <BaseButton {...props} ref={ref} />;
});

```

сейчас `Props` не экспортятся поэтому много кода, можно договориться и экспортить, тогда нужно будет писать так

```
import { Button as BaseButton, Props } from '@gpn-design/uikit/Button';
import {
  ComponentWithAs,
  forwardRefWithAs,
} from '@gpn-design/uikit/__internal__/src/utils/types/PropsWithAsAttributes';

export const Button: ComponentWithAs<Props, 'button'> = forwardRefWithAs<Props>((props, ref) => {
  return <BaseButton {...props} ref={ref} />;
});
```

**Comment by c1n1k** [comment]
проблема не решается, если передеать тег `a`, то возникает ошибка с атрибутом `href`

**Comment by gizeasy** [comment]
я проверил этот кейс, все нормально
в компоненте headerMenu
![image](https://user-images.githubusercontent.com/13190808/90255734-5b125e80-de4d-11ea-880e-9482ec263a76.png)

**Comment by c1n1k** [comment]
обновил все компоненты до версии 1.6.1, сделал простой реэкспорт кнопки, всё равно сборка падает, теперь только в других компонентах, но ошибка уже на ref

**Comment by gizeasy** [comment]
Раньше использовался innerref теперь просто ref. Пройдись по проекту поменяй.
