### ISSUE TITLE
Автоматизация темизации

### ISSUE THREAD

**Issue by dimabo** [gpn-prototypes/ui-kit#9]
Сейчас источником истины о значениях цветов выступают css-файлы тем. Это хорошее решение, потому что а) в коде, б) понятно версионирование, в) встраивается в релизный цикл.
Есть недостатки:

1. Забирать эти значения из кода можно только в рамках фреймворка whitepaper (потому что whitepaper-специфичный css)
2. Комментарии о семантике цветов доступны только в css-файле и не транслируются никуда. Для дизайнеров интерфейсов это высокий порог вхождения -- нужен акк на гитхабе и умение им пользоваться.
3. При появлении сквозных изменений -- много ручной работы. Затраты на актуализацию.

Предлагаю:
1. Использовать json-файл для каждой темы
2. В его структуре предусмотреть а) имя; б) значение; в) от какого цвета функционально зависим; г) семантический комментарий.
3. Написать скрипт -- генератор css-файла из json'a

Профиты:
1. Можно будет транслировать за рамки фреймворка
2. Можно использовать json для интеграции с figma -- сквозные изменения!
3. Более прозрачная и понятная документация для разработчиков и дизайнеров
4. Возможность запилить Хороший сторибук с поиском по значениям, поиском вхождений, кнопками копирования и прочими няшками.

**Comment by midler** [comment]
По описанию напоминает Дизайн Токены. 
Есть несколько готовых реализаций. 

Так же есть готовый плагин для Сторибука:
https://github.com/UX-and-I/storybook-design-token

Демо (правый сайдбар):
https://storybook-design-token.netlify.com/?path=/story/components--avatar
